name: Perpetual VDS with tmate

on:
  workflow_dispatch: # Запуск вручную
  repository_dispatch:
    types: [restart-vds] # Автоперезапуск

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355 # 5ч 55м, оставляем 5 минут на бэкап

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Data from Backup
        run: |
          if [ -f "vds_backup.zip" ]; then
            echo "Backup file found. Restoring..."
            unzip -o vds_backup.zip -d ./
          else
            echo "No backup found. Starting fresh."
          fi

      - name: Setup and Run tmate
        id: tmate_session
        run: |
          sudo apt-get update && sudo apt-get install -y tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          TMATE_SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "TMATE_SSH_URL=${TMATE_SSH}" >> $GITHUB_OUTPUT
          echo "========================================================================="
          echo "SSH connection string: ${TMATE_SSH}"
          echo "========================================================================="

      - name: Save SSH Link to File
        run: echo "${{ steps.tmate_session.outputs.TMATE_SSH_URL }}" > ssh_link.txt

      - name: Keep VDS Alive
        run: |
          echo "VDS is running. Will shut down and backup in approximately 5 hours 45 minutes."
          sleep 20700

      - name: Create Backup
        run: |
          echo "Creating data backup..."
          zip -r vds_backup.zip . -x ".git/*" "vds_backup.zip" "ssh_link.txt"

      - name: Commit Backup and SSH Link
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "VDS Backup & SSH Link Auto-Update"
          file_pattern: "vds_backup.zip ssh_link.txt"

      - name: Trigger Next VDS Run
        run: |
          echo "Triggering VDS restart..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "restart-vds"}'
